### PR TITLE
#176 fix nf and df return types from i18.js

### PR DESCRIPTION
**Pull request by EduwHS**

### CODE REVIEW

**Comment by zewa666** [comment]
thanks

**Comment by EduwHS** [comment]
@zewa666  the dist is updated everyday? Or you manually trigger the build process? I ask because I would like to update the project where I'm using this library.
Thanks.

**Comment by zewa666** [comment]
@EduwHS this will happen when a new release is out.
If you can't wait, meanwhile you can build the app yourself in your branch using `gulp build` and push it. Then just switch to your branch instead of the official plugin

**Comment by EduwHS** [comment]
Thanks @zewa666

**Pull request merged**
