### PR TITLE
fix(attributes): allow omitting attributes in options

### PR DESCRIPTION
**Pull request by JeroenVinke**
fixes https://github.com/aurelia/i18n/issues/13

### CODE REVIEW

**Comment by zewa666** [comment]
so in case of omitting we'd use a default one? Would that be `t` as this is the currently primarily registered one?

**Comment by JeroenVinke** [comment]
Hmm. the [docs](https://github.com/aurelia/i18n#translating-via-html-attributes) says that the plugin defaults to `['t','i18n']`, but I don't see this anywhere in the code? I understand it as: if you don't configure attributes in the options, it will default to configure `t` and `i18n`

**Comment by zewa666** [comment]
Yep I see that was a misinformation. Currently it will do so in the i18n service initialization https://github.com/aurelia/i18n/blob/master/src/i18n.js#L28 but not at the place you pointed out. Over there we'd need to create an alias as well for the defaults, so besides the check for the SUCCESS case of the if clause we also need to register manually the i18n alias in the FAIL case.

This should then match with the docs and provide the features promised. Any other things you see here? If not either you can send the updated PR or I'll happily modify yours and merge it. Please also take care of our linting setup, which you'll get by installing eslint for the IDE of your choice and pointing it to this conf-file https://github.com/aurelia/i18n/blob/master/.eslintrc

**Comment by JeroenVinke** [comment]
All yours :smile: you don't have to use this PR if that's easier for you

**Comment by zewa666** [comment]
Ok, after some git black magic I managed to merge it :)

**Pull request merged**
