### PR TITLE
Resolves #236: Typings requires allowSyntheticDefaultImports = true f…

### LINKED ISSUE #236: Workaround for allowSyntheticDefaultImports = true
In aurelia-i18n@2.0.0, in the typings file (node_modules/aurelia-i18n/dist/aurelia-i18n.d.ts)  on **line 2**:

```typescript
import i18next from 'i18next';
```

This line causes typescript compile errors if your project's tsconfig.json has not been explicitly configured to allow synthetic default imports.

```
{
    "compilerOptions": {
        "allowSyntheticDefaultImports": true // Required compiler option to make aurelia-i18n work
    }
}
```

This constraint could easily have been avoided by simply changing the line to

```typescript
import * as i18next from 'i18next';
```

Can you please fix this?
I believe this may complicate things for many developers trying to use the plugin...

### PR DESCRIPTION
**Pull request by josundt**
I forked the repo and then I first tried to make my singe line change to ./src/i18n.js as described earlier (please refer issue #236).

I then built the project and saw that the ./dist/aurelia-18n.d.ts was generated the way I wanted it to, but when running the tests afterwards, most of them were broken.

Even though I am not very experienced with Babel, when I debugged the tests, I discovered how the Babel transpiler injects a method "_interopRequireWildcard" to simulate default exports for CommonJS modules.

So to my current reenlightened knowledge, **_Babel_** expects you to use the syntax...
```javascript
import theModule from "./the-module.js";
```
...when importing **_CommonJS_** modules, whileas **_TypeScript_** by default expect you to use the syntax...
```typescript
import * as theModule from "./the-module.js";
```
...for CommonJS modules unless the _allowSyntheticDefaultExports_ compiler option is switched on (default is off). When this is switched on, _both_ import syntaxes are accepted by TypeScript.

The ideal solution for aurelia-i18n to accommodate TypeScript projects is therefore that the source file ./src/i18n.js continue to use the current syntax required by your Babel build/transpilation, but to ensure that the .d.ts file uses the wildcard import syntax expected by TypeScript projects using aurelia-i18n.

I have added a simple search-replace fix to your gulp build script that does exactly as described; please review it. You may know the build script better than me and you may know a better way than my search-replace technique to do accomplish the same, but my change anyway does exactly what is needed.

PS! This change will not be a breaking change for projects using the .d.ts file.

I hope the pull request will be accepted. It is as earlier mentioned unreasonable that the aurelia-i18n typings file imposes certain TypeScript compiler options to projects using the plugin. The allowSyntheticDefaultImports compiler option is lightly to be unwanted for the rest of the project's code base.

### CODE REVIEW

**Comment by zewa666** [comment]
@josundt thanks for taking the time to walk through it. You've now came to the same conclusion as me, but I kinda like the idea of simply replacing the import for TS. Could you just exclude the generated dist file, as we're making those during the release process and with the fixed up gulp task that should work out of the box.
Please also make sure to sign our CLA so that we can merge your PR.

@EisenbergEffect are you fine with the proposed approach?

**Comment by EisenbergEffect** [comment]
Makes sense.

**Comment by josundt** [comment]
BTW: This is in my opinion an issue that if possible should be fixed in "babel-dts-generator". This would fix the problem closer to its origin.

At transpile time, Babel can distinguish CommonJS source modules from other module types, and "babel-dts-generator" should translate the import statements for CommonJS modules to TypeScript compliant import statements.

**Comment by zewa666** [comment]
@josundt thanks for the contribution

**Pull request merged**
