### PR TITLE
Binding Behavior for dates and numbers

### PR DESCRIPTION
**Pull request by thesmallbang**
Added binding behaviors for dates and numbers

### CODE REVIEW

**Comment by thesmallbang** [comment]
Is this a normal ci/circleci failure? I haven't modified any item that could have caused a failure with packages.

**Comment by zewa666** [comment]
@thesmallbang thanks for your contribution :+1: 
@EisenbergEffect this ones ready to merge. Please take a look at the failing CircleCI thingy, seems like JSPM times out being used without credentials. Could you also check whether @thesmallbang has signed the CLA?

**Comment by EisenbergEffect** [comment]
@zewa666 CLA is confirmed. Just make sure to run the tests locally and it will be ok for now.

**Comment by zewa666** [comment]
@EisenbergEffect everything ok, ready for merge

**Comment by EisenbergEffect** [comment]
@zewa666 Can you go ahead and do the merge? It's good to have other team members in the git history.

**Pull request merged**
