### PR TITLE
Add typings instructions for i18n-xhr-backend library

### PR DESCRIPTION
**Pull request by ErikSchierboom**

### CODE REVIEW

**Comment by zewa666** [comment]
@ErikSchierboom thank you for the great contributions ... seems though that this one got out of sync when merging your other PRs. Could you please rebase?

Also please change the commit message to conform to [our guidelines](https://github.com/DurandalProject/about/blob/master/CONTRIBUTING.md#commit)

**Comment by ErikSchierboom** [comment]
@zewa666 Sure! I've just rebased to the latest master and updated the PR.

**Comment by ErikSchierboom** [comment]
@zewa666 I've also updated the commit message. Hopefully, I've correctly interpreted the guidelines.

**Comment by zewa666** [comment]
@ErikSchierboom pretty close, it would have been docs(CONTEXT), so e.g. docs(typings): ...
but this is good enough I'll update it when merging.

oh ok so meanwhile they're hosting the typings file on DT? that sounds great. Did you experience any issues/differences to our one provided?

**Comment by ErikSchierboom** [comment]
@zewa666 I've updated the commit message.

As for the differences, it's almost a drop-in replacement. You can see the differences [in this diff](https://www.diffchecker.com/ohnqia2J). The main difference is that there is now a dedicated options definition. If one upgrades to the DefinitelyTyped version, this could break existing code, but only if they were already using the library incorrectly (so that would be a good thing).

**Comment by zewa666** [comment]
Alright, thank you for digging into this one 👍

**Pull request merged**
