### PR TITLE
Master

### PR DESCRIPTION
**Pull request by mcginkel**
Added an implementation of an i18next backend which uses aurelia’s
loader to fetch json files with translation resources. Great way to
load from a bundle.

### CODE REVIEW

**Comment by zewa666** [comment]
@mcginkel allright that looks great and works. Now what is left is to update the docs and give some instruction on how to setup the backend loader.

That should happen in this file: https://github.com/aurelia/i18n/blob/master/doc/article/en-US/i18n-with-aurelia.md
I'd recommend putting the description before the section TypeScript support. If you could add this to your PR I'll give another look at it, fix up stuff and get the PR merged asap

**Comment by zewa666** [comment]
@mcginkel thanks for the contribution I'll add the docs

**Comment by mcginkel** [comment]
Hi vildan

I wrote the doc, but got a merge conflict. Had no tool to merge markdown nicely.

Kees

Met vriendelijke groet,

Kees van Ginkel

**Comment by zewa666** [comment]
@mcginkel can you just create a new PR, we'll fix the conflicts over there then.

**Pull request merged**
