### PR TITLE
fix(versions): update dependencies

### PR DESCRIPTION
**Pull request by zewa666**
updates dependencies, adds aurelia-dependency-injection in order to fix
bundling issue

fixes issue https://github.com/aurelia/i18n/issues/72

### CODE REVIEW

**Comment by zewa666** [comment]
@EisenbergEffect can you please check out whether i've correctly updated package.json and config.js to include all necessary information for newer jspm versions? Tested this with 0.16.15 and it works as expected.

**Comment by valichek** [comment]
@zewa666 there is still a problem with dependency, it uses `"intl": "npm:intl@1.1.0"` but in code:
```javascript
loader.normalize('Intl.js', i18nName)
```

**Comment by EisenbergEffect** [comment]
@zewa666 The package.json looks fine. Please see the comments from @valichek and make sure that the name in the config.js matches the name you are calling `normalize` with.

**Comment by zewa666** [comment]
@valichek thanks for the hint. Totally forgot about that one.

@EisenbergEffect I think we're good now

**Comment by EisenbergEffect** [comment]
Release coming in about 5 minutes.

**Pull request merged**
