### PR TITLE
feat(signaling): provides TBindingBehavior

### PR DESCRIPTION
**Pull request by zewa666**
adds the new TBindingBehavior to cowork with the TValueConverter for signaled changes. Auto signal on locale changes

fixes issue https://github.com/aurelia/i18n/issues/6

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
@zewa666 Does this result in any changes to the way that the library is used? Or is it something that happens automatically. Can you explain a bit?

**Comment by zewa666** [comment]
It adds another way to translate content. Instead of `<span>${ 'KEY' | t }</span>` users now can do `<span>${ 'KEY' & t }</span>`. Its essentially a shortcut for `<span>${ 'KEY' | t & signal:'SIGNALID' }</span>`. Going to release a new README with additional examples later

**Comment by EisenbergEffect** [comment]
@zewa666 So, I would imagine that the preferred mechanism would be to use the binding behavior rather than the value converter. Is that correct?

**Comment by zewa666** [comment]
@EisenbergEffect essentially yes, since it provides all the features of the TValueConverter (by calling it under the hood) + signaling.

**Comment by zewa666** [comment]
@EisenbergEffect can we merge this one?

**Comment by EisenbergEffect** [comment]
I will get it in shortly.

**Comment by EisenbergEffect** [comment]
@zewa666 Actually, you have rights to push to master. Go ahead and perform the merge. If you want to make a release, just let me know and I'll take care of it.

**Comment by zewa666** [comment]
oki doki @EisenbergEffect, ready for release

**Pull request merged**
