### PR TITLE
doc(README): explain how to use with webpack to load submodules

### PR DESCRIPTION
**Pull request by Jenselme**
See #84

### CODE REVIEW

**Comment by zewa666** [comment]
thanks good idea. Have you already signed our CLA? I'd need that in order to merge your PR.

**Comment by Jenselme** [comment]
@zewa666 I have. Is there something I have to do to prove it?

**Comment by zewa666** [comment]
Nope, we're fine. @EisenbergEffect can always check in the signee list. Thanks

**Comment by EisenbergEffect** [comment]
Yes, CLA is confirmed. Thanks!

**Pull request merged**
