### PR TITLE
import was using incorrect syntax for typescript

### PR DESCRIPTION
**Pull request by dinkzilla**
Typescript doesn't allow this "default" import syntax for CommonJs modules when compiling to ES5, so you have to use the old CommonJs syntax to get it to import. The following will also work:

import * as i18next from 'i18next';

But I prefer the older syntax so that it is super clear that this is a compatibility issue.

### CODE REVIEW

**Comment by zewa666** [comment]
@dinkzilla did you experience any issues with the previous way? So far for me everything worked as expected.

**Comment by dinkzilla** [comment]
Yes. When building I our project without the change I get the following error:

C:\Code\DynamicPricing\node_modules\aurelia-i18n\dist\aurelia-i18n.d.ts:1:8                                                                          
    Module '"C:/Code/DynamicPricing/node_modules/i18next/index"' has no default export.

**Comment by dinkzilla** [comment]
Interesting - one of our team members has reported not getting this error. We're investigating. I'll let you know later today what we find.

**Comment by zewa666** [comment]
welcome to the fun TypeScript world :)

**Comment by dinkzilla** [comment]
After investigation, our remote dev was mistaken, he is getting the same error. 

We are compiling to es2015 now, not es5, and that error still pops up. I think my understanding that it was an issue with the transpiling target was incorrect. I based that on this article:

http://www.jbrantly.com/es6-modules-with-typescript-and-webpack/

But after closer reading it seems that when he uses the term "targeting" he means the package you're importing, not what you are transpiling to. Which, if I'm understanding everything correctly, means this issue will be an issue no matter what. Unfortunately, typescript's own documentation on this issue has ambiguity issues of it's own.

I'm not sure why though you would be fine and our entire team gets an error without this change. Any thoughts?

**Comment by atsu85** [comment]
@dinkzilla, try following TypeScript compiler option:
`    "allowSyntheticDefaultImports": true,`
I added it exactly because of i18next, see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/10006

**Comment by zewa666** [comment]
@atsu85, @dinkzilla guys can we move this discussion into an issue, as I think that way it has more value for other followers as well. As a last note, I've used `allowSyntheticDefaultImports` when I tried it out as well. So maybe this is the missing point

**Comment by dinkzilla** [comment]
Apparently [an issue](https://github.com/aurelia/i18n/issues/56) has been around since January on this.

This conversation has already taken place there (apologies for not find it, or the other pull request that you referenced).

@EisenbergEffect calls it a ["bug in typescript"](https://github.com/aurelia/i18n/issues/56#issuecomment-171042651). But this appears to be by design, not a bug, as the presence of the setting indicates. It also seems to be suggested in their [documentation](https://www.typescriptlang.org/docs/handbook/modules.html) (search "export ="). 

Is there any harm to using one of the two syntaxes which actually work? If not, why require an extra setting?

**Comment by mxl** [comment]
@dinkzilla If you look at https://github.com/i18next/i18next/blob/master/index.js then you'll see that i18next has no default export. So you should import it like:
```typescript
import * as i18next from 'i18next';
```
If you want to import it like it have default export:
```typescript
import i18next from 'i18next';
```
then you should enable `"allowSyntheticDefaultImports": true` TypeScript compiler option and compiler will generate for each default import a wrap that simulates default export:

```javascript
function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
var _i18next = require('i18next');
var _i18next2 = _interopRequireDefault(_i18next);
```

**Comment by mxl** [comment]
I agree with @dinkzilla that `i18next` should be imported as:
```typescript
import * as i18next from 'i18next';
```
or
```typescript
import i18next = require('i18next');
```
because otherwise you have to enable `allowSyntheticDefaultImports` option that's not acceptable for everyone.

**Comment by dinkzilla** [comment]
I've moved the discussion to [the issue from January](https://github.com/aurelia/i18n/issues/56), but this issue was closed for some reason.

**Comment by dinkzilla** [comment]
Sorry, I didn't realize I was in my master branch when I started pushing my commits. I'm working on making the change to the src file and building it. I'll work it out and fix the pull request shortly.

**Comment by EisenbergEffect** [comment]
@zewa666 Where are we at with this?

**Comment by dinkzilla** [comment]
I've had a very busy week. I'll see if I can't work it out this weekend and
submit a pull request.

**Comment by PWKad** [comment]
@zewa666 is the "allowSyntheticDefaultImports" the proposed solution or is a PR pending with perhaps another solution?  Just checking on what to review / test out.

**Comment by zewa666** [comment]
Honestly I'm not sure what the best path forward is. Looking forward to what @dinkzilla will come up with

**Comment by dinkzilla** [comment]
Sorry, I have a work deadline next Friday, so I've been a bit overloaded and didn't get a chance to come back and give an update, but I did do some research about this over Thanksgiving. 

In summary, what I've found was: 
- For compatibility with older modules, such as those which use CommonJS, ES6+ needs a way to import the entirety of their "exports" object.
- While most javascript transpilers have decided that the ES6+ default import syntax is fine for this, the Typescript community thinks that default importing should be reserved for only explicit ES6+ default importing. 
- Typescript's solution was to offer a specific import syntax for these scenarios, which is structured like the old CommonJS import syntax, to make it clear what you are doing.
- Noting that the rest of the javascript community was going a different way, they eventually offered a transpiler option to "allowSyntheticDefaultImporting".

So if you're trying to build a framework that works with any transpiler, I think you have two options:
1. Require people to turn that on allowSyntheticDefaulting (in Aurelia's case, set that up in the skeleton), which the Typescript purest will not like (although there are enough libraries that work this way that you can easily debate how egregious this really is).
2. Instead of writing in ES6+, you could write it in Typescript (which would basically just require changing that one import line I think) then transpile it to ES6+ as part of your build process. I haven't really had time to look into how this works though, and if it will in this case.

**Comment by zewa666** [comment]
@dinkzilla you've exactly nailed the point I was talking about why TS is making life so complicated :)
Honestly my personal preference is to keep things as they are and promote `allowSyntheticDefaultImporting`. So instead of merging this issue, can I ask everybody to give the docs section about TypeScript a thorough look on how we can better express the situation? I did some updates today, which I hope will clarify things

**Pull request closed without merging**
