### PR TITLE
Add support for culture names

### PR DESCRIPTION
**Pull request by masterpoi**
i18n.language returns "nl-NL" on my machine, which is not defined in translations. There should probably also be better exception handling here to make clear that the language/culture is not supported.

### CODE REVIEW

**Comment by zewa666** [comment]
@masterpoi thanks for the contribution, have you signed already our CLA?

**Comment by masterpoi** [comment]
@zewa666 Yes

**Comment by zewa666** [comment]
@masterpoi great, after looking through your commit, may I ask you to add a unit test verifying your change? Also a short hint about the change in the README might help others.

**Comment by EisenbergEffect** [comment]
CLA confirmed.

**Comment by zewa666** [comment]
@masterpoi sorry but I've to ask you additionally to rebase your work off the recent merge.

**Comment by masterpoi** [comment]
I've merged with the other changes and added some tests. I've also modified the code to properly load all relevant translation into i18next so it can do it's own fallback thing.
I'm not sure what to put in the README  since this seems to me to be something internal to relativeTime and more of a bugfix. It is probably only relevant to translation authors, since now the translations file behaves as you would expect from i18next.

**Comment by zewa666** [comment]
You are right, nevermind the README, was thinking about something wrong here :)

Thanks for the extra mile you went, great work :+1:

**Pull request merged**
