### PR TITLE
Add dependent modules to aurelia/build/resources in package.json.

### PR DESCRIPTION
**Pull request by bartlenaerts**
Added the list of dependent modules ("aurelia-i18n/t", "aurelia-i18n/nf", "aurelia-i18n/df", "aurelia-i18n/rt") to the property aurelia/build/resources in package.json.

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
@bartlenaerts **Thank you for contributing this pull request!** We're truly excited and honored to have you as a member of our community. We look forward to working together with you to further build the Aurelia platform.

We noticed that you haven't yet signed our CLA. We would appreciate it if you would consider doing that for us. Before signing, please take a few minutes to read [our contributing guidelines](https://github.com/DurandalProject/about/blob/master/CONTRIBUTING.md). These guidelines will help get you up to speed on how our community likes to operate and how the pull request process works. Once you have read that, assuming you are in agreement, simply [sign our online CLA](https://docs.google.com/forms/d/1Npd68d32UDUKUYuCDDrW0VN5Lv8p-a6Ziaa2JFKp6Cg/viewform?c=0&w=1).

After you've signed, please ping this issue to let us know and we'll get your improvements merged in.

Thank you again!
The Aurelia Team

**Comment by EisenbergEffect** [comment]
@niieani Can you review this for correctness?

**Comment by niieani** [comment]
@EisenbergEffect it's good. Technically when we're referencing the local package it doesn't need to be prefixed by the package name, i.e. instead of `"aurelia-i18n/t"`, simply `"t"`. But both ways should work -- the `templating-resources` package currently references its resources by full name too.

**Comment by bartlenaerts** [comment]
@EisenbergEffect I've signed the CLA. I didn't yet update any version numbers. I'll leave that for you guys! Thanks for merging!

**Comment by EisenbergEffect** [comment]
Excellent. Thanks all. Merging now.

**Pull request merged**
