### PR TITLE
Make rt value converter accept ISO8601 strings and empty values

### PR DESCRIPTION
**Pull request by manuel-guilbault**

### CODE REVIEW

**Comment by zewa666** [comment]
@manuel-guilbault could you tell me what the use case for this would be?

**Comment by manuel-guilbault** [comment]
Mostly to be consistent with the other converters.
```nf``` and ```df``` both support empty values (currently ```rt``` will throw an error if a non-```Date``` value is passed, including ```null``` or ```undefined```), and ```df``` supports ISO8601 strings, so it makes sense to me that the two converters dealing with dates accept the same input.

**Comment by manuel-guilbault** [comment]
Also, supporting ISO8601 strings makes it easier to use values deserialized from JSON, since this is the standard format into which Date objects are serialized. Currently, developers have to manually transform any JSON deserialized Date into a Date object in the view-model, since it cannot be done in the view (without using another converter, that is).

**Comment by zewa666** [comment]
Ok sounds reasonable I'd say. Could you just make the commit message confirm to our guidelines, so it will be automatically inserted in the changelog when released?

**Comment by manuel-guilbault** [comment]
Done, sorry about that.

**Pull request merged**
