### PR TITLE
Correct spelling of Deferred in i18n.js

### PR DESCRIPTION
**Pull request by cornillemichiel**
Minor typo in source (Defered => Deferred). I only edited the /src file in browser, not the /dist files.
This is my first GitHub PR ever, so be gentle 👍

### CODE REVIEW

**Comment by zewa666** [comment]
The bad part is that this would introduce a breaking change for whoever used this prop. Proper spelling is important but im not sure its worth the trouble in this case. I'd keep this one open for when we really need to introduce a large BC

**Comment by Alexander-Taran** [comment]
`i18nextDefered = i18nextDeferred = {...`

???

**Comment by zewa666** [comment]
That would nevertheless still show both props in intellisense which might be even more misleading right?

**Comment by bas080** [comment]
Maybe `defer` the change when there is a better reason for a mayor version bump.

**Comment by zewa666** [comment]
There are plans to port the whole plugin over to TypeScript like other official repositories. During that undertaking I think we can do this fix as well as simplify the overall setup story, which would justify a major version bump.

@davidtimovski nothing is evil about mayor version bumps, the trouble though is that you either do a hard break and force everyone to upgrade for upcoming features, or maintain a multi-path strategy. Later is absolutely not justified for a small typo. There's nothing unprofessional about keeping the story easy for consumers and not having them overhaul their apps dependencies over and over again.

**Comment by zewa666** [comment]
done in new TS port branch https://github.com/aurelia/i18n/blob/port-to-typescript/src/i18n.ts

**Pull request closed without merging**
