### PR TITLE
fix npm install problem

### PR DESCRIPTION
**Pull request by k2s**
see #68

### CODE REVIEW

**Comment by gingerik** [comment]
Same here:

```
$ jspm --version
0.16.27
$ jspm install aurelia-i18n@0.4.10
     Updating registry cache...
     Looking up npm:aurelia-i18n
     Looking up npm:aurelia-binding
     Looking up npm:aurelia-event-aggregator
     Looking up npm:aurelia-loader
     Looking up npm:aurelia-templating
     Looking up npm:aurelia-templating-resources
     Looking up npm:i18next/i18next
     Looking up npm:intl
     Looking up npm:aurelia-metadata
     Looking up npm:aurelia-pal
     Looking up npm:aurelia-task-queue
     Looking up npm:core-js
     Looking up npm:aurelia-logging
     Looking up npm:aurelia-path
     Looking up npm:aurelia-dependency-injection

warn Using local override for npm:core-js@2.1.1
     Downloading npm:core-js@2.1.1

warn Using local override for npm:core-js@2.0.3

err  Repo npm:i18next/i18next not found!

warn Installation changes not saved.
```

@k2s - Shouldn't you update all three occurrences of `i18next`?

**Comment by k2s** [comment]
@gingerik: no, the format is valid for jspm sub-section

**Comment by EisenbergEffect** [comment]
@zewa666 Where are we at on this?

**Comment by zewa666** [comment]
sry that it took me so long, was quite a busy week. Yep just tried it now and the above works and fixes npm issues :+1:

**Comment by zewa666** [comment]
@EisenbergEffect can you create a new release?

**Comment by EisenbergEffect** [comment]
It will release shortly.

**Comment by EisenbergEffect** [comment]
Released.

**Pull request merged**
